---
- hosts: build
  gather_facts: no
  remote_user: ubuntu
  become: yes
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=Dockerfiles dest=/tmp
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io, awscli
        state: present
        update_cache: yes
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: docker
    - name: Build an image and push
      docker_image:
        build:
          path: /tmp/Dockerfiles/build_image
        name: build
        state: present
        source: build
    - name: run the build in a docker container
      docker_container:
        name: build
        image: build
        state: started
        volumes:
          - /data
    - name: docker volume inspect
        command: docker volume inspect --format '{{ .Mountpoint }}' data
        register: data_inspect
    - name: Wait until the string "completed" is in the file foo before continuing
      wait_for:
        path: '{{ data_inspect }}/foo'
        search_regex: completed
    - name: run the prod in a docker container
        docker_container:
          name: prod
          image: build
          state: started
          volumes:
            - /data1