---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=Dockerfiles dest=/tmp
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io, awscli
        state: present
        update_cache: yes
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: docker
- hosts: build
  gather_facts: no
  become: yes
  tasks:
    - name: Creating build image
      shell: docker build --no-cache -t build /tmp/Dockerfiles/build_image
    - name: run the build in a docker container
      docker_container:
        name: build
        image: build
        auto_remove: yes
        state: started
        volumes: /var/lib/docker/volumes/build:/var/build_data
    - name: docker_repository - Log into ECR registry and force re-authorization
      shell: aws s3 sync /var/lib/docker/volumes/build s3://my-bucket-kmi/build
    - name: remove ibuild image
      shell: docker rmi build
- hosts: prod
  gather_facts: no
  become: yes
  tasks:
    - name: run the prod in a docker container
      docker_container:
        name: prod
        image: tomcat:9.0
        ports:
          - "8080:8080"
        recreate: yes
        state: started
        volumes:
          - /var/lib/docker/volumes/build:/usr/local/tomcat/webapps
    - name: docker_repository - Log into ECR registry
      shell: aws s3 sync s3://my-bucket-kmi/build /var/lib/docker/volumes/build